### ISSUE TITLE
Import of keepassxc fails

### ISSUE THREAD

**Issue by kschlesselmann** [roddhjav/pass-import#90] opened 2019-09-24 04:10 UTC
I'm on arch linux here (installed from AUR) and the import of our keepassxc passwords fail with
```
pass import -p PRADA/imported keepassxc prada-secrets.kdbx
Password for <_io.TextIOWrapper name='prada-secrets.kdbx' mode='r' encoding='utf-8'>:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 1990, in <module>
    main(sys.argv)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 1942, in main
    importer.parse(file)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 798, in parse
    with PyKeePass(path, password) as keepass:
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 42, in __init__
    transformed_key=transformed_key
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 62, in read
    transformed_key=transformed_key
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 324, in parse_file
    with open(filename, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper
```

I haven't digged into the code but it looks like pass-import is maybe delegating a wrong object as `path` to pykeepass?

**Comment by roddhjav** [comment] 2019-09-24 09:47
Hi, 

This is a know bug, fixed on the master branch, see a8f56cc6a85362ed20f46c1360c87fdd213b890c. 

However, you don't have to install from the master branch, you can use the keepass importer, that is not touched by the bug and use the same class:
```
pass import keepass file.kdbx
```

**Comment by kschlesselmann** [comment] 2019-09-26 06:20
Hm … that leaves me with
```
pass import -p PRADA/imported keepass prada-secrets.kdbx 
Password for prada-secrets.kdbx:
  w  'bytes' object has no attribute 'encode'
 [x] Error: prada-secrets.kdbx is not a valid exported keepass file.
```

**Comment by elvirolo** [comment] 2019-10-31 11:44
@kschlesselmann It is caused by a bug in pykeepass, which has been solved upstream. See https://github.com/libkeepass/pykeepass/issues/152#issuecomment-530631736

**Comment by roddhjav** [comment] 2019-10-31 13:03
Thank for the tip. Indeed that seems to be the same issue. @kschlesselmann could you confirm?

**Comment by Araly** [comment] 2019-11-10 16:22
same issue when trying to import for keepassx2

**Comment by roddhjav** [comment] 2019-11-10 16:29
Did you use the last version of pykeepass?

If yes, using the (last commit on the) master branch you can use the `-vvv` option to show the python trace.

Alternatively, you can export your data in CSV and import it using the `keepassx2-csv` importer.

**Comment by Araly** [comment] 2019-11-10 16:43
I'm using version 3.1.1 of pykepass and 2.6-2 of pass-import

**Comment by roddhjav** [comment] 2019-11-10 16:46
Ok, so it is not related to https://github.com/libkeepass/pykeepass/issues/152#issuecomment-530631736

So it should be something else, could you install pass-import from git and using the `-vvv` option send the python trace you get.

**Comment by Araly** [comment] 2019-11-10 17:41
```
$ pass import keepass file.kdbx  
Password for Downloads/araly.kdbx:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 1990, in <module>
    main(sys.argv)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 1942, in main
    importer.parse(file)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 812, in parse
    attachment['data'] = att.data
  File "/usr/lib/python3.7/site-packages/pykeepass/attachment.py", line 45, in binary
    return self._kp.binaries[self.id]
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 479, in binaries
    if elem.attrib['Compressed'] == 'True':
  File "src/lxml/etree.pyx", line 2478, in lxml.etree._Attrib.__getitem__
KeyError: 'Compressed'

```

**Comment by roddhjav** [comment] 2019-11-10 19:24
This is different, it's related to the attachment import. I will need to investigate on it to see if it is a pass-import bug or a pykeepass issue.

So if you don't have attachment, you should probably import from a CSV file.

**Comment by roddhjav** [comment] 2019-11-10 19:57
After a few tests, it's because your database does not have compression enabled and pykeepass fail when reading the attachments. See https://github.com/libkeepass/pykeepass/issues/181

**Closed** 2019-11-20 13:18 UTC
