### ISSUE TITLE
Traceback error when import of keypass2.xml 

### ISSUE THREAD

**Issue by christian-weiss** [roddhjav/pass-import#52] opened 2018-11-18 22:40 UTC
Command:
`pass import keepass keypass2.38_onUbuntu.xml`

Error:
```
Traceback (most recent call last):
  File "/usr/lib/password-store/import/import.py", line 776, in <module>
    main(sys.argv)
  File "/usr/lib/password-store/import/import.py", line 732, in main
    importer.parse(file)
  File "/usr/lib/password-store/import/import.py", line 334, in parse
    self._import(root)
  File "/usr/lib/password-store/import/import.py", line 513, in _import
    self._import(group, path)
  File "/usr/lib/password-store/import/import.py", line 516, in _import
    entry['title'] = self._getpath(xmlentry)
  File "/usr/lib/password-store/import/import.py", line 551, in _getpath
    return os.path.join(path, title)
  File "/usr/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

```
pass version
============================================
= pass: the standard unix password manager =
=                                          =
=                  v1.7.1                  =
=                                          =
=             Jason A. Donenfeld           =
=               Jason@zx2c4.com            =
=                                          =
=      http://www.passwordstore.org/       =
============================================
``````

```
python3 --version
Python 3.6.5
```

```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

How to solve that? (How to debug?)

**Comment by roddhjav** [comment] 2018-11-19 00:42
Hi, could you tell me which version of pass-import you are using?

**Comment by christian-weiss** [comment] 2018-11-19 06:19
It was late night, i forgot to mention, sorry.

I installed it yesterday via:
```
git clone https://github.com/roddhjav/pass-import/
cd pass-import
sudo make install
```
so it is most up-to-date

**Comment by roddhjav** [comment] 2018-11-19 13:52
Ok, I was able to reproduce the bug. This is because in your xml export file you have either a `'Group'` name or an `'Entry'` title that is empty and therefore that return nothing as value.

As an fast fix you can edit your xml file and add a name. Otherwise a real fix will come soon.

**Comment by roddhjav** [comment] 2018-11-19 22:59
It should be fixed now.

**Comment by christian-weiss** [comment] 2018-11-20 11:20
Confirm. Issue is fixed.

**Closed** 2018-11-20 11:20 UTC
