### ISSUE TITLE
canj't install on arch

### ISSUE THREAD

**Issue by chovy** [roddhjav/pass-import#131] opened 2021-01-05 06:46 UTC
`yay -S pass-import` gets a key error.

**Comment by cassfalg** [comment] 2021-03-28 20:26
The missing pgp key? I am not sure if that is really your problem, since you're problem description is extremely vague...

But -- I have just installed it successfully on arch from the AUR repositories, after adding the pgp signing key that is used to sign the repository. Instructions for that are in the PKGBUILD, which you should glance over anyway. They are also here in the installation description of the project's readme. Not for Arch, but in the next segment for Debian.

I'd recomment closing this issue since it can not be reproduced.

**Closed** 2021-05-15 17:19 UTC
